# Generated by Django 6.0.3 on 2026-03-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(choices=[('All', 'All Skin Types'), ('Oily', 'Oily'), ('Dry', 'Dry'), ('Combination', 'Combination'), ('Sensitive', 'Sensitive')], default='All', max_length=20),
        ),
    ]
